### ISSUE TITLE
Command Map: Running vs Command

### ISSUE THREAD

**Issue by ddarbyson** [capistrano/sshkit#118]
I'm trying to modify all commands to switch user to `deploy` before executing any commands. Ie, in my Capistrano setup:

```ruby
SSHKit.config.command_map = Hash.new do |hash, command|
  hash[command] = "/usr/bin/sudo /bin/su - deploy -c '#{command}'"
end
```

Produces the following when running `deploy:check`

```bash
DEBUG [c875aad6] Running /usr/bin/sudo /bin/su - deploy -c 'ssh -i /home/deploy/.ssh/deploy.pem -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o StrictHostKeyChecking=no test@exmaple.com exit' on 
DEBUG [c875aad6] Command: ssh -i /home/deploy/.ssh/deploy.pem -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o StrictHostKeyChecking=no test@exmaple.com exit
```

You can see that "Running" output looks correct, however "Command" is not being updated.

Am I missing something? 

Bottom line, i'm trying to switch current user to `deploy` before executing any cap tasks. 

I'm trying to avoid running switching users before running `cap` and bake the `deploy` user right into my Capistrano tasks without using SSHKIT block `as 'deploy' do`. This would require rewriting every custom cap task and furthermore overwriting Capistrano default tasks. Suggestions are welcome. Thank you.

**Comment by leehambley** [comment]
Please see https://github.com/capistrano/sshkit/issues/262
