### ISSUE TITLE
Weird logging behaviour in upload! and download!

### ISSUE THREAD

**Issue by daniel-rikowski** [capistrano/sshkit#133]
I've been experimenting with the `upload!` and `download!` methods and I noticed that their callback (`transfer_summarizer`) is outputting a lot of progress messages when processing large files.

For a 80 MB file I get roughly 5000 log lines at log level "debug" and still about 500 at log level "info".

1. I guess the number debug outputs are to expected, although personally I think logging every callback is a bit excessive.
2. Additionally the rule for logging info messages seems to be flawed:

		if percentage > 0 && percentage.round % 10 == 0
		  info message
		else
		  debug message
		end

It looks like the original intention is to output only 10% steps (0, 10, 20 ... 100%) but this code logs each and every callback when the percentage is near a 10% step.

For an 80 MB file I get:

	DEBUG Uploading ./target/package.tar.gz 89.42%
	DEBUG Uploading ./target/package.tar.gz 89.44%
	DEBUG Uploading ./target/package.tar.gz 89.46%
	DEBUG Uploading ./target/package.tar.gz 89.49%
	 INFO Uploading ./target/package.tar.gz 89.51%
	 INFO Uploading ./target/package.tar.gz 89.53%
	 INFO Uploading ./target/package.tar.gz 89.55%
	 INFO       ... about 40 more lines ...
	 INFO Uploading ./target/package.tar.gz 90.45%
	 INFO Uploading ./target/package.tar.gz 90.47%
	 INFO Uploading ./target/package.tar.gz 90.49%
	DEBUG Uploading ./target/package.tar.gz 90.51%
	DEBUG Uploading ./target/package.tar.gz 90.53%
	DEBUG Uploading ./target/package.tar.gz 90.55%

			
My guess is that `upload!` and `download!` are not intended and/or tested with large files.

I'm willing to improve the code, but I'm not sure where to start. 

As far as I understand the number of log messages starts to increase if the file size is about 100 times higher than the chunk size. (> 1,6 MB) because then we start to get callbacks with steps smaller than 1%.

As a test I changed the line 

        if percentage > 0 && percentage.round % 10 == 0

into			

        if percentage > 0 && percentage.round(digits) % 10 == 0

where `digits` increases with the number of total chunks. (`total / ch[:chunk_size]`) It greatly decreases the number of info logs, about 3-4 around the 10% steps but it that is a very dissatisfying solution.

I doubt there is a way to fix it without saving some kind of state between callbacks, but if someone has a good idea I'll gladly spend some more time on this.

**Comment by johnkharvey** [comment]
I also have this issue-- our cap code uploads one large file using upload!.
It would be nice if the code could determine file-size, and if it was a large file, perhaps output each single whole percent (i.e. 1%, 2%, 3%).  I definitely agree that this is strange-looking output, and if the network gets slow, it's very hard to know if the process has hung, or if things are still moving forward.

**Comment by svsa** [comment]
Dumb question, sorry.
You suggest using rsync in cap3, but i have no idea how to do that, nor to use scp. I want to upload a large file from local to remote. Help, please?!

**Comment by leehambley** [comment]
Simply `execute(:rsync, 'your options here')`

**Comment by svsa** [comment]
Oh. :)
Thanks

**Comment by rmoriz** [comment]
When using in a release-pipeline those upload-messages are quite too verbose. Setting the default logger for all messages from INFO to WARN to circument this, seems not a good idea either. Maybe a config option to disable or reduce the `transfer_summarizer` output can be introduced?

**Comment by leehambley** [comment]
Closing, see #334
