### ISSUE TITLE
NoMethodError: undefined method `recv' for #<IO:fd 47>

### ISSUE THREAD

**Issue by jasonl** [capistrano/sshkit#150]
Intermittetently during deploys, the deploy will fail around 50% of the time with the following error - however executing `cap deploy` again (sometimes several attempts will be required) will usually produce a successful deploy.

Environment: Capistrano v3.2.1, SSHKit 1.4.0, net-ssh 2.9.1 under Ruby 2.1.1 deploying a Rails 4.0.2 application.

```
cap aborted!
NoMethodError: undefined method `recv' for #<IO:fd 47>
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/buffered_io.rb:65:in `fill'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:86:in `next_packet'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:210:in `block in wait'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:208:in `loop'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:208:in `wait'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:87:in `initialize'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `new'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/net-ssh-2.9.1/lib/net/ssh.rb:202:in `start'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/backends/connection_pool.rb:24:in `create_or_reuse_connection'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:173:in `ssh'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:126:in `block in _execute'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:123:in `tap'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:123:in `_execute'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:62:in `test'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/capistrano-3.2.1/lib/capistrano/tasks/deploy.rake:216:in `block (3 levels) in <top (required)>'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/jason/.rvm/gems/ruby-2.1.1@avetars/gems/sshkit-1.4.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => deploy:set_previous_revision
(See full trace by running task with --trace)
The deploy has failed with an error: #<NoMethodError: undefined method `recv' for #<IO:fd 47>>
```

**Comment by murphyslaw** [comment]
:+1:

**Comment by guymaliar** [comment]
same error happens here, behind a proxy ...

**Comment by leehambley** [comment]
I can't reproduce this at all, in the end I guess the problem belongs to `Net::SSH`, btu I need some steps to reproduce this :( Is there some proxy I can install locally and route everything through, which proxy

**Comment by victorcoder** [comment]
@leehambley If you're using OSX you could enable "Remote Login" in System settings -> Sharing and configure the proxy like: `set :ssh_options, proxy: Net::SSH::Proxy::Command.new("ssh username@localhost -W %h:%p")`

**Comment by leehambley** [comment]
@victorcoder perfect, so an `ssh` proxy (tunnel) is the problem here, not standard network proxies, etc. Thanks for the feedback.

**Comment by Janther** [comment]
@leehambley also deploying to a single machine behind a proxy doesn't have issues.
But on multiple machines, I get this error on random steps (but I'm 95% certain its only on parallel tasks).

**Comment by skanev** [comment]
Same here and neither of the solutions above work for me.

**Comment by emma-borhanian** [comment]
Encountered this as well

**Comment by leehambley** [comment]
If we can't post some constructing reproduction steps I'm going to lock the issue against future "me too" comments, I've never run into this and can't replicate it. (Even given what was discussed above) 

Anything:

* How often does it happen?
* When?
* What kind of network/proxy
* Is it 100% repeatable, or does it happen at random?
* Has *anyone* added a `debugger` and caught this `NoMethodError`?

And, why are we still discussing it here when the backtrace leads to `Net::SSH`!?

**Comment by skanev** [comment]
I'd love to elaborate a bit.

* It begun with a migration to Capistrano 3. Everything worked fine until then.
* It happens randomly when I deploy. Every now and then. I haven't found a pattern. Thus, most of the deploys are fine, but occasionally, I need to start a new one, and hope it's going to pass.
* I'm SSH-ing to a single machine over the good old internet, and I use that machine to ssh to other machines, forwarding my agent. There are no VPNs or no proxies involved, as far as I can tell.

I haven't added a `debugger`, but I'm going to start debugging now and share results if I reach any.

**Comment by guymaliar** [comment]
Hi guys,

We've managed to tackle the problem, it isn't necessarily related to Capistrano,
for us the problem was that our ssh server was dropping connections.

We changed in `sshd_config`

```
MaxStartups <number of concurrent connections needed>
ClientAliveInterval 60
ClientAliveCountMax 5
```

And we're not experiencing these any more.

**Comment by leehambley** [comment]
Thanks @guymaliar !

**Comment by mgodwin** [comment]
Awesome!  @guymaliar did you make that change on the proxy server?

**Comment by guymaliar** [comment]
Exactly, that's the server that gets hit with all of the connections first ...

**Comment by johncalvinyoung** [comment]
Sweet. Spent 90 minutes yesterday spelunking in Net::SSH internals trying to catch that exception... never did, btw. This makes so much sense though...

**Comment by leehambley** [comment]
I wonder if Net::SSH is doing some magic where it "upgrades" an FD to a "socketish FD" if it looks/acts like a socket, otherwise I can't imagine why this would be a NoMethodError

**Comment by mgodwin** [comment]
Hmmm... making the change for only `MaxStartups` didn't fix it for me.  I also added in the `ClientAliveInterval` and `ClientAliveCountMax` and still got `undefined method 'recv'`.  I'll see if I can do some debugging later tonight.

**Comment by guymaliar** [comment]
By the way I also added in our `deploy.rb` file

```ruby
SSHKit::Backend::Netssh.pool.idle_timeout         = 60
SSHKit::Backend::Netssh.config.connection_timeout = 60
```

Don't know if that does help or just voodoo but having MaxStartups on `N * 1.5` connections (on the jump box of course) where N is the maximum number of servers being deployed to, did the trick.

Hopefully it'll help you guys as well.

**Comment by amw** [comment]
I've changed `MaxStartups` on the jump host to a really big number and it didn't help. I've also read the logs (/var/log/secure) and there's no mention of sessions closed due to limits or anything else suspicious.

I'm using `ProxyCommand` set in my `~/.ssh/config` not in Capistrano/SSH-Kit config. Also using agent forwarding and SSH compression. Recently I've added `ControlMaster` to the mix, but I've been getting the error even before that.

**Comment by makered** [comment]
Just upgraded from Capistrano 2 to 3.4.0. Using SSH over proxy, same problem, deployment fails in different steps with error similar to:

<code>NoMethodError: undefined method `recv' for #\<IO:fd 21></code>

Tried setting (on the proxy):

MaxStartups 20
ClientAliveInterval 60
ClientAliveCountMax 5

without success.

**Comment by makered** [comment]
More observations:

1. The error is only encountered when we deploy from our CI server, which is on the same LAN as the target hosts, bridged by a fast, low latency connection. Same deployment triggered from a remote location over VPN succeeds every time.

2. It seems that the chance of failure increases with the number of targets. For me the rate is ~50% for 2 and almost 100% for 4.

I am not too familiar with how SSHKit/Net-SSH works but my guess would be a possible race condition.

**Comment by leehambley** [comment]
Thanks for the information @makered, I still can't reproduce this, but more information is helping. I have a raspberry pi cluster at home on a gigabit lan, I wonder if I can setup a fuzzing script to bash them with something trivial to try and reproduce it, even if it is racy.

Could you tell me *which* shell command is running when you see the problem, is it setting up a new connection, or part way through a `git checkout` which takes a few seconds, or is it more like a "test" or "mkdir" that should complete essentially instantly?

**Comment by amw** [comment]
I had a Terminal tab still open with six of these failures when I got your message.

1 & 6. ~/.rbenv/bin/rbenv exec bundle exec whenever --update-crontab

Not a very short lived task, but it doesn't start Rails env and takes less than a second to run when executed directly. Here two servers (out of 4) finished the task before error:

INFO [e97521ff] Finished in 1.794 seconds with exit status 0 (successful).
INFO [b2780a08] Finished in 1.831 seconds with exit status 0 (successful).

2 & 4. /usr/bin/env chmod +x /tmp/app/git-ssh.sh

This failed twice. Basically instant. On both occasions three servers (out of 4) finished:

INFO [404180fc] Finished in 0.831 seconds with exit status 0 (successful).
INFO [282c8d5e] Finished in 0.832 seconds with exit status 0 (successful).
INFO [1af617cf] Finished in 0.834 seconds with exit status 0 (successful).

3. /usr/bin/env [ -d ~/.rbenv/versions/2.2.1 ]

Also instant. Just at the start of `cap deploy`. None of the servers finished.

5. This one time I got the error after seeing all four "Finished in .. seconds" messages, but before seeing any new "Running new command as". That's odd. As if there was some socket access between two server commands.

Let me know if I can do something to help you – I can reproduce this problem pretty easily. That means, it almost kills my whole deployment strategy.

**Comment by amw** [comment]
Very often the deploy fails on one of the last commands, the one that removes old release directories:

/usr/bin/env rm -rf ~/app/releases/20150509160115 ~/app/releases/20150511133125

That's also rather quick and it fails really often.

**Comment by makered** [comment]
It varies for me. I have seen the error occur either very early in the deployment process or on some later task and usually on fast-running tasks. The most recent failure was on:

<code>mkdir -p /home/deploy/app/myapp/shared/config</code>

**Comment by mattbrictson** [comment]
This bug has me completely stumped. Maybe with all the brainpower on this thread we can get to the bottom of it. Here is a bunch of new information to keep the conversation moving:

---

**How can the `recv` method possibly be missing?**

For me this is the heart of the matter. All signs point to some bug in MRI itself, because it makes no sense to me.

I modified the `open` method of [`net/ssh/proxy/command.rb`](https://github.com/net-ssh/net-ssh/blob/v2.9.2/lib/net/ssh/proxy/command.rb#L68) to insert a `puts` statement:

```ruby
class << io
  def send(data, flag)
    write_nonblock(data)
  end

  def recv(size)
    read_nonblock(size)
  end
end
puts "Proxy::Command #{io.inspect} has recv? #{io.respond_to?(:recv)}"
io
```

We can see that the code is opening the singleton class of `io` and adding the `send` and `recv` methods. So of course, `io.respond_to?(:recv)` will be `true`, right? Yes. *Usually.*

Occasionally (approximately 1 of 10 deploys), the `puts` line outputs:

```
Proxy::Command #<IO:fd 15> has recv? false
```

Followed by the dreaded:

```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployer@app: undefined method `recv' for #<IO:fd 15>
NoMethodError: undefined method `recv' for #<IO:fd 15>
```

Again, this makes no sense to me why the `recv` method would be missing, despite being explicitly declared.

---

**My environment**

* ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
* capistrano (3.4.0)
* sshkit (1.7.1)
* net-ssh (2.9.2)

I am able to reproduce the bug approximately 1 of 10 deploys, provided that I modify my `~/.ssh/config` to enable connection multiplexing, like this:

```
Host *
  Compression yes
  ControlMaster auto
  ControlPath /tmp/ssh_mux_%h_%p_%r
  ControlPersist 10s
  ServerAliveInterval 15
  ServerAliveCountMax 2
```

If I remove the `Control*` directives, the deploys always work.

I've also disabled SSHKit connection pooling, in an attempt to make the errors more frequent, because the stack trace always points to where a new connection is being started.

```ruby
SSHKit::Backend::Netssh.pool.idle_timeout = 0
```

I am deploying to two servers, each of which is specified in `.ssh/config` like this:

```
Host gateway
  ForwardAgent yes
  User deployer
  HostName aaa.aaa.aaa.aaa

Host app
  User deployer
  ProxyCommand ssh root@aaa.aaa.aaa.aaa exec nc bbb.bbb.bbb.bbb %p

Host db
  User deployer
  ProxyCommand ssh root@aaa.aaa.aaa.aaa exec nc ccc.ccc.ccc.ccc %p
```

**Comment by mattbrictson** [comment]
OK, I've figured it out: **defining methods with `class << obj ... end` is not thread safe in MRI!**

Here's a simple script to demonstrate:

```ruby
require "thread"

def define_singleton_methods_in_thread
  Thread.new do
    100_000.times do
      obj = Object.new
      class << obj
        def one
        end

        def two
        end

        def three
        end
      end
      puts "FAIL" unless obj.respond_to?(:three)
    end
  end
end

# Test with 2 threads
2.times.map { define_singleton_methods_in_thread }.map(&:join)
```

On my machine this outputs:

```
FAIL
FAIL
FAIL
```

So I guess the only options here are:

1. Turn off threading (i.e. use `:in => sequence`)
2. Guard `Net::SSH.start` with a mutex
3. Open a net-ssh PR to rewrite the code to avoid using singleton methods
4. Somehow get this fixed in MRI?

Thoughts on how to proceed, @leehambley ?

**Comment by makered** [comment]
Great find @mattbrictson! 

Curious though, I have another app that I have been deploying (Capistrano 3.2.1, sshkit 1.5.1, net-ssh 2.9.1) to multiple hosts in a similar fashion for months without getting this error.

**Comment by mattbrictson** [comment]
@makered You'll see in my script I had to bump the number of iterations up to 100,000 just to get three failures, so the race condition (or whatever it is) is fairly rare. There are so many factors in terms of timing, thread scheduling, i/o latency, etc. that hitting this bug will probably seem random.

The only sure things are that:

* `ProxyCommand` must be present for the bug to be occur (non-proxied hosts don't touch the affected code)
* The deploy must involve multiple hosts using `:in => :parallel`

The rest is up to chance. :smiley:

**Comment by mikz** [comment]
I think it increases with number of hosts. It almost never occurred with 4 but with 10 it was happening pretty often. Amazing find @mattbrictson !

**Comment by mattbrictson** [comment]
Thanks @mikz ! My next steps are:

1. Open a PR for net-ssh (I have an idea for rewriting the code not to use `class << io` that will solve this)
2. File a bug at <https://bugs.ruby-lang.org>

**Comment by scharfie** [comment]
@mattbrictson -- for (1), it seems that using `obj.extend(SomeModule)` does not suffer the thread-safe issues that `class << self` does.  On my machine using your script, I was getting the "FAIL" lines as expected.  I changed the code to use `extend` and no more 'FAIL' lines:

```
require "thread"

module MyMethods
  def one
  end

  def two
  end

  def three
  end
end

def define_singleton_methods_in_thread
  Thread.new do
    100_000.times do
      obj = Object.new
      obj.extend(MyMethods)
      puts "FAIL" unless obj.respond_to?(:three)
    end
  end
end

# Test with 2 threads
2.times.map { define_singleton_methods_in_thread }.map(&:join)
```

I'm not sure if this is what you were alluding to with your idea, but it seems a viable approach.

**Comment by leehambley** [comment]
Excellent work @mattbrictson that's quite the find!

Another data point here, although it seems pretty damned conclusive: 

```
$  cat > mattbrictson.rb
require "thread"
# ...snip...
# Test with 2 threads
2.times.map { define_singleton_methods_in_thread }.map(&:join)

$  ruby ./mattbrictson.rb
FAIL
FAIL
FAIL
FAIL
$  ruby ./mattbrictson.rb
FAIL
FAIL
$  ruby ./mattbrictson.rb
FAIL
FAIL
FAIL
$ ruby -v
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
```

Someone hand that man a :beers:.

I just went looking for bugs, and see you already [opened one](https://bugs.ruby-lang.org/issues/11153). I see you commented there that you couldn't reproduce it on `trunk`, I think this might be why:

 * [Singleton class expression (class << obj) should make be indivisual namespaces
](https://bugs.ruby-lang.org/issues/10943)

I do think we might be able to work around this in net-ssh, @delano has it in maintenance mode, but he'll take patches with tests.

**Comment by mattbrictson** [comment]
Thanks for verifying, @leehambley !

Good news is that my [patch](https://github.com/net-ssh/net-ssh/pull/240) to net-ssh was merged! If you are affected by the `NoMethodError recv` bug, please try upgrading your net-ssh dependency to `:github => "net-ssh/net-ssh", :branch => "master"` and test.

**Comment by mgodwin** [comment]
When trying to upgrade my net-ssh dependency to what @mattbrictson mentioned, I'm getting the following error:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /mnt/gem/net-ssh-private_key.pem
An error occurred while installing net-ssh (2.9.3.beta1), and Bundler cannot continue.
```

I'm assuming that has to do with this line in the README:

> Since building the gem requires the private key if you want to build a .gem locally please use the NET_SSH_NOKEY=1 envirnoment variable:
> rake build NET_SSH_NOKEY=1

Maybe I'm missing something obvious.  Is there anything special you need to do?  (exporting that variable doesn't seem to help) I can't imagine that I actually need to have the directory `/mnt/gem/..`

Thanks

Also, my gemfile looks like:

```
gem 'net-ssh', :github => "net-ssh/net-ssh", :branch => "master"
```

**Comment by leehambley** [comment]
I'm on my phone, but I guess you have to use
http://bundler.io/v1.3/man/bundle-config.1.html to set the env var, or
bundler will clean the env.

**Comment by mattbrictson** [comment]
@mgodwin It seems to work for me, using the same Gemfile entry you showed. 

```
$ bundle install
Fetching git://github.com/net-ssh/net-ssh.git
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
[snip]
Using net-ssh 2.9.3.beta1 (was 2.9.2) from git://github.com/net-ssh/net-ssh.git (at master)
```

Maybe you need to upgrade to a newer version of bundler? Mine is:

```
$ bundle -v
Bundler version 1.9.6
```

**Comment by mgodwin** [comment]
@mattbrictson good call - bundler was 1.6.3 and upgrading it fixed the problem.  Testing out the fix!

**Comment by mgodwin** [comment]
And it worked!  I'll post again if I get the error message, but so far looking promising.  I almost never could get a deploy to succeed prior to this (sshing into 8 machines).  Awesome work @mattbrictson!

**Comment by makered** [comment]
net-ssh patch confirmed effective from my testing against 4 hosts with numerous attempts.

@mattbrictson you are my hero!

**Comment by charneykaye** [comment]
+1 editing the `sshd_config` on the bastion server

**Comment by leehambley** [comment]
Thanks to @mattbrictson for his amazing work debugging this, I'm closing the issue as Net::SSH is finally  about to release v2.10.0 - however note that this version *requires* Ruby 2.0. 

Since we can't fix this without that patch, that essentially means that SSHKit in this setup with a gateway and many hosts is *very* likely to continue to be broken on 1.9x. 

At some near point in the future I'm going to bump our minimum required version to 2.x to isolate ourselves from this bugginess.
