### ISSUE TITLE
Execute output is no longer formatted

### ISSUE THREAD

**Issue by buildmaster** [capistrano/sshkit#152]
as raised here: https://github.com/capistrano/capistrano/issues/1086

The output from the following cap task:
```
desc "list running processes"
task :list do
  on roles(:all), in: :sequence do
    execute "pm2 list"
  end
end
```
produces different output on 1.2.0 of SSHKIT vs 1.5.1

on 1.2.0 it's colorized and formatted correctly:
![screenshot 2014-06-24 09 55 31](https://cloud.githubusercontent.com/assets/19946/3377910/569d95ce-fbe4-11e3-9804-49c6e08915da.png)
on 1.5.1 it's ignoring the ANSI colours
![screenshot 2014-06-24 09 55 07](https://cloud.githubusercontent.com/assets/19946/3377916/5edab0a0-fbe4-11e3-9b05-3bf2a3e0db2c.png)

Both commands were run on the same OS X 10.10 client against ubuntu 13.10 (same servers for both so same versions of pm2.

is there something I missed with the upgrade?

**Comment by leehambley** [comment]
Closing as we've had quite some changes in the formatter, and we're probably going to make https://github.com/mattbrictson/airbrussh the default formatter going forwards.
