### ISSUE TITLE
Add support for default_shell

### ISSUE THREAD

**Issue by primerano** [capistrano/sshkit#162]
I have some folks who use csh as their default shell and the capistrano deploy scripts fail in various ways when this shell is used since it isn't POSIX.

Would it be possible to add an option that prefixed all the ssh commands with a shell invocation to get around the user's default /etc/passwd defined shell?

Sort of like the old set :default_shell, "/bin/bash" option.

From capistrano-2.15.5/lib/capistrano/configuration/actions/invocation.rb
        # * :shell - says which shell should be used to invoke commands. This
        #   defaults to "sh". Setting this to false causes Capistrano to invoke
        #   the commands directly, without wrapping them in a shell invocation.

**Comment by ikari7789** [comment]
Has there been any progress on this?

**Comment by glaszig** [comment]
i think i need this as well to get rid of capistrano-rbenv.

**Comment by leehambley** [comment]
Closing this issue, if someone writes a sane patch, I'd be happy to merge something. I'm afraid of having many, many multiple ways to get a shell, the differences between login/non-login and all the other things already cause massive confusion, doubly so when people wrap things in the special command map, and use flags like `--login` on their shells.
