### ISSUE TITLE
Remove whoami check in "as"

### ISSUE THREAD

**Issue by smw1218** [capistrano/sshkit#167]
For a restricted user (ie. a user that doesn't have full root access via sudo), this requires that "whoami" is explicitly enabled in the sudoers file which is silly when I'm just trying to run something else that is enabled for the user:
if ! sudo -u #{@user} whoami > /dev/null
            then echo "You cannot switch to user '#{@user}' using sudo, please check the sudoers file" 1>&2
            false
          fi

**Comment by abhishiv** [comment]
Yes, please this check is indeed very silly. If someone can send a PR to fix this it would be great!

**Comment by leehambley** [comment]
I was clear five years ago when I advised that we're open to taking a patch, but that we designed it this way for a reason. Times change, and good error messages on ops tooling is important. 

The other maintainers and I would be glad to assist with getting a patch to the required standard to be merged if we can maintain our standards.
