### ISSUE TITLE
Inconsistent behaviour when running MCollective rpc commands (cap2 works, SSHKit does not)

### ISSUE THREAD

**Issue by bsnape** [capistrano/sshkit#220]
Hi,

(I originally posted this to https://github.com/capistrano/capistrano/issues/1358#issuecomment-72884579 but @leehambley thought it would be more appropriate to post it here.)

I noticed a weird problem running `mco rpc` commands when upgrading from Capistrano 2 to Capistrano 3. 

Background: we use Capistrano in our deployment pipeline to SSH onto various servers and run various `mco` commands.

In a nutshell: Running `mco rpc` commands fail (hang) when using "Capistrano 3" (in quotes because I tested against `SSHKit` directly) but works fine when using Capistrano 2. I also tried using my own lightweight custom SSH implementation (that I've used in other places) but this doesn't work either.

My (fairly obvious) theory is that Capistrano 2 did something special/different to handle RPC calls.

I've tested this extensively and I've created a repo with examples and documentation: https://github.com/bsnape/sshkit-mco-rpc-bug

I feel like I've hit the limit of my debugging until someone more familiar with the two codebases (cap2/sshkit) can take a look. I think there's plenty of information in my repo and I'm happy to help out in fixing this or adjusting my setup if I'm doing something wrong.

**Comment by bsnape** [comment]
@leehambley regarding your comment here: https://github.com/capistrano/capistrano/issues/1358#issuecomment-72883207, I tried the following:

Works:

```
$ ssh -i ~/.vagrant.d/insecure_private_key vagrant@192.168.2.10 'mco service status httpd'

2 / 2

   middleware.example.net: stopped
        node0.example.net: stopped

Summary of Service Status:

   stopped = 2


Finished processing 2 / 2 hosts in 135.59 ms
```

Still hangs:

```
$ ssh -i ~/.vagrant.d/insecure_private_key vagrant@192.168.2.10 'mco rpc service status service=httpd --json'
```

You mentioned the `ssh` `-c` flag but I'm not sure how that relates in this context (unless I've misunderstood something)?

**Comment by leehambley** [comment]
> You mentioned the ssh -c flag but I'm not sure how that relates in this context (unless I've misunderstood something)?

It doesn't, I was thinking that `$ ssh 'some command'` was `$ ssh -c 'some command'` (but that's bash, which takes a `-c`)… brain fart :) ignore me.

**Comment by leehambley** [comment]
Next step I guess would be to get the pid of the `mco` process, and attach strace to it, and paste the log here if you can, I'd expect it's blocking on write, probably to a file descriptor that it doesn't have because it's a `non-interactive` pty.

Hints: http://www.hokstad.com/5-simple-ways-to-troubleshoot-using-strace
