### ISSUE TITLE
Regression: SSHKit 1.7.0 removes command completion status from logs

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/sshkit#226]
In SSHKit 1.6.0 the successful completion status of each command was logged, like this:

```
INFO [b02151f4] Finished in 0.141 seconds with exit status 0 (successful).
```
In SSHKit 1.7.0 these log messages are gone. SSHKit 1.7.0 logs the command but never logs the "Finished" message.

This regression is due to this commit: https://github.com/capistrano/sshkit/commit/aa278dbeb4b1f931c875d413a22b22971085189c#diff-6285ece7ab8d7c6b765599fa5ee02b01

Before, the `exit_status` was updated first, and then the command was logged, like this:

```ruby
cmd.exit_status = data.read_long
output << cmd
```

Now in 1.7.0, the order is flipped, such that the command is logged *before* the status is updated:

```ruby
output << cmd
cmd.exit_status = data.read_long
```

As a result, the logger never receives the command with the exit status. This is very important information that is now missing from the log output.

**Comment by leehambley** [comment]
See `v1.7.1`, a quick report, and following fix, and great quality fix at that.. just pushed a patch release with your changes

**Comment by leehambley** [comment]
https://rubygems.org/gems/sshkit/versions/1.7.1

**Comment by mattbrictson** [comment]
Thanks! :smiley:
