### ISSUE TITLE
test() does not run as specified user

### ISSUE THREAD

**Issue by Quagh** [capistrano/sshkit#228]
I don't know if it should or not, but I am under the assumption it should as I wrapped it in `as :user do`.

```ruby
desc 'Random task'
task :mytask do

    on roles(:all), in: :parallel do
    
        as :root do
    
            if test('! id -u deploy')
                info 'Deploy user does not exist'
            end
            
        end
            
    end
end
```

which executes

```
/usr/bin/env id -u deploy
```

when I want it to do

```
sudo -u root /usr/bin/env id -u deploy
```

or something.

**Comment by leehambley** [comment]
`if test('! id -u deploy')` contains whitespace and is therefore not "modified" using the scope changing methods above, see https://groups.google.com/forum/#!topic/capistrano/o63Yzy5L9Ao

**Comment by Quagh** [comment]
Ah, didn't know it had to be done for `test()` too. Thanks! Using `unless test(:id, '-u', 'deploy', '>/dev/null', '2>&1')` now.

And as you've said, some documentation would be great :) Right now it's 20% writing code and 80% googling and figuring out how something works.

**Comment by leehambley** [comment]
Lucky that the topic came up so recently in the mailing list, actually. It's surprising, but the reasons as stated there still apply, it's less than ideal, I wish we could make it better, but you're stuck with it I'm afraid! 

Glad the work around works. Have fun!
