### ISSUE TITLE
NoMethodError: undefined method `gateway=' for #<SSHKit::Backend::Netssh::Configuration:0xa03da18>

### ISSUE THREAD

**Issue by ArunSakthivel** [capistrano/sshkit#229]
I have defined gateway server details in the config/deploy/production.rb
`SSHKit.config.backend.configure do |ssh|
 ssh.gateway = "user@<server_name>"
 end
`

And I'm getting below error, while run below command
`$  cap production rvm:check`

` NoMethodError: undefined method gateway=' for # <SSHKit::Backend::Netssh::Configuration:0xa03da18>`

In Gemfile.
`gem 'sshkit', '~> 1.7.1'`

**Comment by leehambley** [comment]
Where did you find `sshkit.gateway=` documented?

**Comment by ArunSakthivel** [comment]
https://github.com/capistrano/sshkit/blob/7a2eac30bb834b9f5e04785b633b09c8a7712773/EXAMPLES.md

**Comment by mattbrictson** [comment]
Hi @ArunSakthivel, the gateway support you are referring is from the dead, un-merged PR #134. There is no gateway configuration option in the current version of SSHKit.

@leehambley can you close this issue?
