### ISSUE TITLE
can't use capture and assign a variable from outside the on block

### ISSUE THREAD

**Issue by innovia** [capistrano/sshkit#231]
I am using thor with sshkit

when i try this:
````ruby
def capture(command)
  on self.public_dns do
     capture command
  end
end

status  = capture("cat ~/test")
status => [#<Thread:0x007f8f6b0192d8 dead>]
````
status is returned as thread dead object

how can i assign it? like in capistrano

**Comment by mattbrictson** [comment]
Keep in mind that `on` may execute on multiple hosts. If the structure of your program guarantees that `self.public_dns` is a single host, then you could do something like this:

```ruby
def capture(command)
  result = ""
  on self.public_dns do
     result << capture(command)
  end
  result
end
```

**Comment by leehambley** [comment]
This is not a Ruby support channel, sorry.
