### ISSUE TITLE
switch user before switching directory

### ISSUE THREAD

**Issue by JeanMertz** [capistrano/sshkit#232]
According to the examples, this should work:

```ruby
as :root do
  puts capture(:whoami)
  puts capture(:pwd)
  within '/var/log/nginx' do
    puts capture(:whoami)
    puts capture(:pwd)
  end
end

```

however, the result is this:

```
root
/home/myuser
cap aborted!
Exception while executing as myuser@app.me: whoami exit status: 1
whoami stdout: Nothing written
whoami stderr: bash: line 0: cd: /var/log/nginx: Permission denied
```

I need to switch to root, because the directory can only be accessed by that user.

**Comment by makered** [comment]
I am experiencing a possibly related issue. Two users on the system, user1 is privileged and user2 is not. When connecting (capistrano 3.4.0) with user1 as a primary user from a task that does <code>as :user2 do</code>  I get:

<code>Running /usr/bin/env if ! sudo -u user2 whoami > /dev/null; then echo "You cannot switch to user 'user2' using sudo, please check the sudoers file" 1>&2; false; fi as user1@192.168.1.25</code>

It seems that the above test should be done as <code>sudo -i -u user2</code> (works fine when manually ran on server)?

**Comment by leehambley** [comment]
```
       -i [command]
                   The -i (simulate initial login) option runs the shell specified in the passwd(5) entry of the target user as a login shell.  This means that login-specific resource
                   files such as .profile or .login will be read by the shell.  If a command is specified, it is passed to the shell for execution.  Otherwise, an interactive shell is
                   executed.  sudo attempts to change to that user's home directory before running the shell.  It also initializes the environment, leaving DISPLAY and TERM unchanged,
                   setting HOME, MAIL, SHELL, USER, LOGNAME, and PATH, as well as the contents of /etc/environment on Linux and AIX systems.  All other environment variables are
                   removed.
```

That seems to conflict with our preference for [`non-login`, `non-interactive shells`](http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/)?

**Comment by makered** [comment]
True, adding -i is just what seemed to work on Ubuntu from my observation. 

User switching via sudo aside, I found a workaround where I can simply change the SSH user to a privileged account when needed as documented [here](http://capistranorb.com/documentation/advanced-features/properties/). Specifically:

```ruby
on roles(:all) do |host|
  execute 'whoami'
  host.user = 'root'
  sudo 'npm install -g forever'
end
```

**Comment by leehambley** [comment]
Maybe I could close this issue, if you'd add something in the appropriate place to the readme or the EXAMPLES?
