### ISSUE TITLE
"can't add a new key into hash during iteration" with jruby-9.0.0.0.pre1

### ISSUE THREAD

**Issue by benben** [capistrano/sshkit#233]
trying to run `cap deploy` with jruby-9.0.0.0.pre1. jruby-1.7.19 works fine.

error:

```
Exception while executing as deployer@172.31.172.174: can't add a new key into hash during iteration
/Users/ben/.rbenv/versions/jruby-9.0.0.0.pre1/lib/ruby/gems/shared/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `execute'
```

please let me know, if you need more information

:sparkling_heart:

**Comment by leehambley** [comment]
Sorry I have never used JRuby I probably can't help you. I've also never seen this error in CRuby, is it JRuby specific, do you know?

**Comment by benben** [comment]
seems like it "can't add a new key into hash during iteration" sound hardly like an java error...
I can imagine two options:
a) refactor the code so that the hash is not chaning while iterating
b) switch parallel off by default for jruby

**Comment by mattbrictson** [comment]
@benben Could you run your deploy again with `--trace` and post the full backtrace of the error? I'm curious what is happening, and it is not clear to me which hash is being changed while iterating.
