### ISSUE TITLE
within release_path do; execute "tar zxf /tmp/test.gz"; end appears to untar test.gz in $HOME

### ISSUE THREAD

**Issue by vrsean** [capistrano/sshkit#265]
This behavior seems counter-intuitive given `within`. The problem was resolved with setting the -C argument to release_path for tar but stumped me a bit.  `execute "pwd"` indicated the proper directly, oddly enough.

The code was executed within the context of `on roles(:assets) do |host|`...basically we are speeding up asset deployment by forking off the compilation of assets in the beginning, tarring up public/assets, and scping that file to /tmp in another task to give some background on the issue.  

We are using sshkit 1.5.1.

Can anyone duplicate this issue or shed some light on it?

Thanks,

--sean

**Comment by leehambley** [comment]
Please re-read [this](https://github.com/capistrano/sshkit#running-commands):

> Note: In SSHKit, the first parameter of the execute / test / capture methods has a special significance. If the first parameter isn't a Symbol, SSHKit assumes that you want to execute the raw command and the as / within / with methods, SSHKit.config.umask and the command map have no effect.

That means you must call:

``` ruby
within release_path do
  execute :tar, '-zxf', '/tmp/test.gz'
end 
```

Not:

``` ruby
within release_path do
  execute "tar zxf /tmp/test.gz"
end 
```
