### ISSUE TITLE
Export environment

### ISSUE THREAD

**Issue by kuon** [capistrano/sshkit#270]
Here:

https://github.com/capistrano/sshkit/blob/32c04ed1cae3608468c3888a727eff54c8bd34fd/lib/sshkit/command.rb#L166

Exporting the environment;

```ruby
"( export #{environment_string}; %s )" % yield
```

Would allow for variable substitution in commands, like so:

```
execute(:psql, '-d $DATABASE_URL')
```

Actually the "effect" is because of the `;` I added before the command, but this requires to export the environment string to allow it's use in subsequent commands.

This would also allow more flexible prefixes.

For example:

```
SSHKit.config.command_map.prefix[:ruby].unshift('some shell script;')
```

to have ruby being executed this way:

```
some shell script; ruby
```

Of course, this is already possible, but the command loses the access to the env var because they are not exported.

**Comment by leehambley** [comment]
Convincing argument, and I'm always in favour of subshells for encapsulation, given how sub shells are a nice analog of what we're doing with ruby blocks in the DSL.

What's the downside, how much stuff will we risk breaking ?

**Comment by kuon** [comment]
I think it should not break anything in the core. I did monkey patch it and it works to deploy a rails app. 

But I am no shell guru, it might change some behavior in some way.

**Comment by leehambley** [comment]
Would you care to prepare a PR and add yourself to the CHANGELOG, etc, I think this is a fair change.

**Comment by kuon** [comment]
https://github.com/capistrano/sshkit/pull/273 should cover this
