### ISSUE TITLE
Deprecate Ruby 1.9

### ISSUE THREAD

**Issue by leehambley** [capistrano/sshkit#272]
In order to switch to a modern Ruby let's [follow the Ruby core team in dropping support for 1.9.x](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/)...

Not simply because we *can*, but because with Ruby 2.x we can enjoy lots of nice new features such as keyword arguments and UTF-8 by default, etc. But also because one of our more serious bugs, via SSHKit comes from Net::SSH, which will be only fixed in a version that depends on Ruby 2.x. 

It's not the best reason to drop support for an old VM, but Ruby 2 is more than two years old!

**Comment by mattbrictson** [comment]
Can we close this issue now that 1.9 was dropped in https://github.com/capistrano/sshkit/commit/847a14b0fa5c635d95929db4f03c5522e5733726 ?
