### ISSUE TITLE
Choose a more liberal licence

### ISSUE THREAD

**Issue by leehambley** [capistrano/sshkit#277]
I'd like to change the licence of SSHKit to something less restrictive.

We have quite a lot of contributors (50+) who would need to OK this, or we have to rewrite their code.

Timeline:

* Today, I'm mailing everyone in the list
* One week from now, I will repeat the mail
* Two weeks from now, we will remove/rewrite code from anyone who disagrees with the new licensing choice.

## How to Agree?

If you agree with the licensing choice, and you are a contributor, please leave a comment with the contents `BOTH`, or `BSD` or `MIT`. If you don't agree with having your code relicensed, leave any other comment. Please also include your email address, e.g.

```
lee.hambley@gmail.com BSD
```

Then I can parse this page, and count off the people who aren't coming with us on this journey.

The current list of contributors with code in `HEAD` that hasn't been superseded or replaced can be generated with:

```
$ git ls-files | GIT_PAGER=cat PAGER=cat xargs -n1 git blame --porcelain | grep 'committer-mail' | awk '{print $2}' | tr -d '<>' | sort -u
```

If anyone can see a flaw with my methodology, I'd be glad of a nudge in the right direction.

**Comment by leehambley** [comment]
Unreachable contributors: `choover@kayak.com`, `devwork@warrentorrance.com`.

(Note: I know that posting email addresses in plaintext might be weird, but given that it's all open for scraping via Github anyway, I think I'm on the right side of the grey line, feel free to call me out if you disagree for any reason)

**Comment by cheald** [comment]
cheald at gmail BSD or MIT

(I don't think `ANY` should be used since it may imply consent for a third unlisted license perhaps `BOTH` instead?)

**Comment by ralovely** [comment]
ralovely@gmail.com ANY #GoForIt

**Comment by Stas-Ghost** [comment]
stas.ghost@gmail.com ANY

**Comment by leehambley** [comment]
> (I don't think ANY should be used since it may imply consent for a third unlisted license perhaps BOTH instead? And I minimally obfuscate my email out of habit. It's all scrapable as you aptly demonstrated!)

Agreed, post edited to reflect that suggestion, thanks!

**Comment by FooBarWidget** [comment]
hongli@phusion.nl BOTH

**Comment by gucki** [comment]
info@corinlangosch.com BOTH

**Comment by hab278** [comment]
Hab278@nyu.edu BOTH

**Comment by seenmyfate** [comment]
`seenmyfate@gmail.com MIT`

I'm genuinely surprised we didn't change this [when we changed the Capistrano license.](https://github.com/capistrano/capistrano/pull/703)

If MIT isn't the best option, I would completely be happy with any non-restrictive license that helps more people to make more use of the project.

**Comment by etehtsea** [comment]
etehtsea@gmail.com BOTH

**Comment by thomasfedb** [comment]
thom@sfedb.com MIT

**Comment by deees** [comment]
tomas.brazys@gmail.com BOTH

**Comment by snaury** [comment]
snaury@gmail.com BOTH

**Comment by chrislewis60** [comment]
chrislewis60@hotmail.com BOTH

**Comment by plu** [comment]
plu@pqpq.de BOTH

**Comment by 0rca** [comment]
little.spring17@gmail.com BOTH

**Comment by kirs** [comment]
MIT

**Comment by kirs** [comment]
shatrov@me.com MIT

**Comment by bruno-** [comment]
bruno.sutic@gmail.com BOTH

**Comment by adammck** [comment]
adam.mckaig@gmail.com BOTH :+1:

**Comment by bhoflack** [comment]
brh at melexis.com BOTH

**Comment by robd** [comment]
robd at robd.co.uk BOTH

**Comment by lmars** [comment]
lewis@lmars.net BOTH

**Comment by Sinjo** [comment]
`chris@sinjakli.co.uk BOTH`

**Comment by x3ro** [comment]
lucas@x3ro.de BOTH

**Comment by kuon** [comment]
kuon@goyman.com BOTH

**Comment by austinpray** [comment]
austin@austinpray.com BOTH

**Comment by korin** [comment]
lisukorin@gmail.com BOTH

**Comment by joelataylor** [comment]
joelataylor@gmail.com BOTH

**Comment by mattbrictson** [comment]
matt@55minutes.com BOTH
matt@mattbrictson.com BOTH

**Comment by betesh** [comment]
iybetesh at gmail  MIT

**Comment by phallstrom** [comment]
philip@pjkh.com BOTH

**Comment by phs** [comment]
phil.h.smith@gmail.com BOTH

**Comment by guillaume-brossard-adsk** [comment]
@leehambley Thanks a lot for your efforts on this!

**Comment by mtrudel** [comment]
mat@geeky.net BOTH

**Comment by leehambley** [comment]
David Grayson agreed via email to me on 2015-08-23

**Comment by jeffawang** [comment]
jeffawang@gmail.com BOTH

**Comment by Mask** [comment]
martin at artcom.de BOTH
any chance getting a free T-shirt? ;-)

**Comment by leehambley** [comment]
> any chance getting a free T-shirt? ;-)

Hehe, I wish, maybe I can sweet talk the Autodesk people, come join us at https://www.harrow.io and I'll arrange a Cap for you :)

**Comment by hab278** [comment]
Free t-shirts!!!

**Comment by townsen** [comment]
nick.townsend at mac.com BOTH
(was away on vacation!)

**Comment by akm** [comment]
akm2000@gmail.com BOTH

**Comment by DejaAugustine** [comment]
contact@dejaaugustine.com BOTH

**Comment by jhollinger** [comment]
jordan.hollinger@gmail.com BOTH

**Comment by rgo** [comment]
contacto@rafagarcia.net BOTH

Thanks Lee and the others :)

**Comment by hobodave** [comment]
github@hobodave.com BOTH

**Comment by leehambley** [comment]
Thanks @hobodave I think we are done now!
