### ISSUE TITLE
Local backend's `capture()` does not strip whitespace by default

### ISSUE THREAD

**Issue by tknerr** [capistrano/sshkit#278]
After switching from netssh backend to local backend, I noticed that `capture()` does not strip the whitespace by default (which it should, according to the readme).

This was using sshkit 1.7.1

**Comment by robd** [comment]
Hi @tknerr 

Up to SSHkit 1.7.1, this behaviour used to be inconsistent between local and sshkit backends, but it is consistent in master (both strip). I guess you are looking at the docs for master. You could use master if you like, or wait for the next release. See #239 and #249 for more info.

**Comment by tknerr** [comment]
Hi @robd, thanks the prompt reply!

I can in fact wait until the next release. I didn't find the two PRs above while scrolling through the issues, and just wanted to make sure it's getting noticed. 

Awesome that you already have a fix for that :-)
