### ISSUE TITLE
Use pristine Bundler environment when executing local commands

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/sshkit#317]
See original discussion here: https://github.com/capistrano/capistrano/issues/1475

To summarize (please correct me if I've missed anything): the Bundler environment used for `bundle cap ...` leaks to any subprocesses by default. This includes commands run by the SSHKit `Local` backend.

This is not desirable by users that are using `Local` for actual deployments. Bundler offers an API to avoid this: `Bundler.with_clean_env`.

Perhaps we should wrap all `Local` commands with `Bundler.with_clean_env` (assuming `Bundler` is defined)? Is there any downside?

**Comment by leehambley** [comment]
It effectively *unloads* bundler, I don't use, or encourage use of the SSHKit local backend. I think people would be better served using the stdlib to manipulate files and start processes, etc. It was a mistake from day one to have the local backend at all.

I can see bundler with clean env breaking things for as many people as it fixes things.

**Comment by chewi** [comment]
Thanks for looking at this. We're still using my proposed fix here and haven't had any issues with it.

**Comment by mattbrictson** [comment]
> I can see bundler with clean env breaking things for as many people as it fixes things.

Fair enough. I'll close this, especially seeing that @chewi has a workaround.
