### ISSUE TITLE
Release 1.9.0 final?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/sshkit#337]
@leehambley Any objections to cutting the final release for SSHKit 1.9.0?

There has been one change since 1.9.0.rc1, which is: **allow procs as command map values** #310. Since this is a new feature and not a fix, maybe we should cut 1.9.0 with a release branch based on the rc1 tag, so that #310 is not included.

Either way, I can take care of building and publishing the release. Let me know.

**Comment by leehambley** [comment]
Sounds good, please do it :)

**Comment by mattbrictson** [comment]
Done in 19bba67.
