### ISSUE TITLE
zlib(finalizer): the stream was freed prematurely. when using compression

### ISSUE THREAD

**Issue by mfazekas** [capistrano/sshkit#342]
```ruby
require 'sshkit'
require 'sshkit/dsl'

SSHKit::Backend::Netssh.config.ssh_options = {compression: true, compression_level: 9}

on 'localhost' do
  ls_output = capture(:ls, '-l')
end
```

It outputs:
```
...
zlib(finalizer): the stream was freed prematurely.
```

the issue is that sshkit doesn't close the net-ssh connection which then cannot close the zlib stream which has finalizer and complains.

as a workaround
```sh
SSHKit::Backend::Netssh.pool.close_connections
```
can be added thanks to https://github.com/capistrano/sshkit/pull/285
see also https://github.com/net-ssh/net-ssh/issues/284

**Comment by leehambley** [comment]
Maybe this issue should be on Capistrano, that we should setup something to call this before the programme exists, we need the pool to keep connections as long as possible.

**Comment by mfazekas** [comment]
Agree on capistrano, i think what sshkit can do is to have a nicer method to close esp in 'dsl', and promote it's use through examples.

**Comment by mattbrictson** [comment]
Would this work instead?

```diff
--- a/lib/sshkit/backends/connection_pool.rb
+++ b/lib/sshkit/backends/connection_pool.rb
@@ -47,6 +47,7 @@ class SSHKit::Backend::ConnectionPool
     @caches.extend(MonitorMixin)
     @timed_out_connections = Queue.new
     Thread.new { run_eviction_loop }
+    at_exit { close_connections }
   end
```

**Comment by mfazekas** [comment]
That should work as well. One corner case is if there is a connection issue, and server not responding user press ctrl+C to abort the program, in this case we might not want to cleanly close the connections as that could be facing the connection issue again. So you might want to do this:
```ruby
   at_exit { close_connections unless $! }
```
