### ISSUE TITLE
deploy project from bitbucket branch to aws ec2 server

### ISSUE THREAD

**Issue by jitendrak1** [capistrano/sshkit#363]
I am trying to my project from bitbuchet to aws ec2 sever, when I follow bundle exec cap staging deploy command then, I got error...

ubuntu@*****ip*****:~/project_folder$ bundle exec cap staging deploy
DEBUG [4550afd9] Running /usr/bin/env which passenger as ubuntu@***IP address***
DEBUG [4550afd9] Command: /usr/bin/env which passenger
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@***IP Address***: Authentication failed for user ubuntu@***IP Address***

Net::SSH::AuthenticationFailed: Authentication failed for user ubuntu@***IP Address***

Tasks: TOP => rvm:hook => passenger:rvm:hook => passenger:test_which_passenger
(See full trace by running task with --trace)
ubuntu@ip-***IP Address***:~/Project_folder$

**Comment by jyr** [comment]
Hi,

What was the mistake?

Thanks
