### ISSUE TITLE
SSHKit, rvm and rake, outside the full Capistrano setup

### ISSUE THREAD

**Issue by JohnSmall** [capistrano/sshkit#374]
I'm trying to use SSHKit to run a set of processes on remote servers. Copying files and doing git pulls works just fine, but when I try to run a shell script which calls a rake task on each remote machine it fails.

I can see that it fails because it can't find rake, because the environment variables aren't set up correctly. I'm using rvm and presumably I need to get that to set up the paths and other environment variables so rake can be found and run. 

I've read through [StackOverflow topic To use bash --login by default with capistrano 3 + sshkit + rvm](http://stackoverflow.com/questions/21360824/to-use-bash-login-by-default-with-capistrano-3-sshkit-rvm) and nothing I've tried works.

I've tried setting the $PATH using 'with xyz do' but that doesn't work either. 

I'm completely stumped. How can I use pure SSHKit, outside Capistrano, to run a set of tasks on remote machines, which require rvm to configure the environment variables so rake works?

**Comment by leehambley** [comment]
Please use the mailing list for support John the GitHub issue tracker is just for bugs and feature requests.

 - https://groups.google.com/forum/#!forum/capistrano

**Comment by leehambley** [comment]
The solution to your problem is literally the 2nd entry in our EXAMPLES file. :-\
