### ISSUE TITLE
Verify net-ssh 4.0 compatibility

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/sshkit#381]
Will sshkit work with net-ssh 4.0?

I noticed that net-ssh 4.0.0.rc2 was just released, and presumably the final version will be coming soon. Can someone double-check whether there are any breaking changes from our perspective, and also verify that our tests pass? I'd appreciate it!

**Comment by mattbrictson** [comment]
net-ssh 4.0.0 was released today. Our tests pass, so it seems we have nothing to worry about. :crossed_fingers:

**Comment by leehambley** [comment]
Congrats to @mfazekas and all the Net::SSH contributors for a solid release 🍾
