### ISSUE TITLE
parallel partial scp upload ?

### ISSUE THREAD

**Issue by grosser** [capistrano/sshkit#394]
is there an option to make scp upload parallel parts ?

for example for a 100mb file upload 3 33mb parts in parallel ... lftp seems to support that, but using it is not trivial ... (seeing 16min -> 6min upload improvement)

**Comment by leehambley** [comment]
I don't think it's plausible given the current APIs, perhaps you'd be better served shelling out to rsync? Which is pretty trivial in the confines of Capistrano/SSHKit as you have access to Rake's `sh` helper?

**Comment by grosser** [comment]
yeah, we'll look into doing that, was hoping someone already ran into this
and it's just not documented :)

**Comment by mattbrictson** [comment]
SSHKit mostly just delegates to net-scp for our scp functionality. A quick glance at that repo indicates that a parallel partial upload is not supported.

https://github.com/net-ssh/net-scp

This is probably too much of an edge case for us to build this as part of SSHKit, IMHO.

**Comment by grosser** [comment]
yeah, move the issue to https://github.com/net-ssh/net-scp/issues/32 thx for the quick reply!
