### ISSUE TITLE
undefined method assign_defaults for Net::SSH:Module

### ISSUE THREAD

**Issue by cmiotto** [capistrano/sshkit#396]
Last version 1.13.0 uses Net::SSH.assign_defaults that was introduced in net-ssh 4.0.0
You should update runtime dependency in gemspec

**Comment by mattbrictson** [comment]
Yikes, good catch! We'll make this a top priority and push a fix this week.

@shirosaki do you have time to look into this? I would prefer to make our code work with net-ssh < 4.0.0 by doing a `respond_to?` check or something similar.

**Comment by mattbrictson** [comment]
For reference, was introduced by https://github.com/capistrano/sshkit/pull/392.

**Comment by mattbrictson** [comment]
@cmiotto Thank you very much for the report and for narrowing it down to the net-ssh dependency!

**Comment by mattbrictson** [comment]
The fix is in master thanks to @shirosaki. I'll publish 1.13.1 tomorrow.
