### ISSUE TITLE
 Host key verification failed when using rsynch in "on primary(:app) do |host|" block

### ISSUE THREAD

**Issue by stepheneb** [capistrano/sshkit#398]
This works fine.
```
task :sync_from do
  run_locally do
    # on primary(:app) do |host|
    roles(:app).each do |host|
      execute :rsync, '-avx --delete', "#{host.user}@#{host.hostname}:/var/www/webapp/shared/public/system/images", "shared/images"
    end
  end
end
```

While entering the block with `on primary(:app) do |host|` generates an `host key` error output (copied at end of this message).

FYI: I only have one host defined.

```
task :sync_from do
  run_locally do
    on primary(:app) do |host|
    # roles(:app).each do |host|
      execute :rsync, '-avx --delete', "#{host.user}@#{host.hostname}:/var/www/webapp/shared/public/system/images", "shared/images"
    end
  end
end
```
The actual rsync commands echoed to the console are identical.

Here's the error with tracing on (actual user and host names elided):

```
** Invoke images:sync_from (first_time)
** Execute images:sync_from
00:00 images:sync_from
      01 rsync -avx --delete <user>@<host>:/var/www/webapp/shared/public/system/images shared/images
      01 Host key verification failed.
      01 rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
      01 rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.1]
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as <user>@<host>: rsync exit status: 255
rsync stdout: Nothing written
rsync stderr: Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.1]
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Command::Failed: rsync exit status: 255
rsync stdout: Nothing written
rsync stderr: Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.1]
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/command.rb:100:in `exit_status='
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/netssh.rb:148:in `execute_command'
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:141:in `tap'
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:74:in `execute'
/Users/stephen/dev/z/zs/lib/capistrano/tasks/images.rake:7:in `block (4 levels) in <top (required)>'
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/stephen/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.12.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => images:sync_from
```

**Comment by leehambley** [comment]
Host key verification failed is an error from the underlying system and doesn't have anything to do with Capistrano or SSH kit.

Is the host key known to your `known_hosts` file? 

I can't see this being an issue with SSHKit (maybe Net::SSH) more likely it's probably a comprehension issue that your system has never connected to `<host>` and thus we can't prompt you for the key, thus we assume it's untrusted.

**Comment by stepheneb** [comment]
host key is fine, have been using cap to deploy to this server for several months

The rsync command works fine from the command line (no host key error).

The rsync command works fine running from a cap task when I use this as the invocation of the block: `roles(:app).each do |host|`

```
$ bundle exec cap development images:sync_from --trace
** Invoke development (first_time)
** Execute development
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke bundler:map_bins (first_time)
** Invoke passenger:bundler:hook (first_time)
** Execute passenger:bundler:hook
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env 
** Invoke rbenv:validate (first_time)
** Execute rbenv:validate
** Invoke rbenv:map_bins (first_time)
** Invoke passenger:rbenv:hook (first_time)
** Invoke passenger:test_which_passenger (first_time)
** Execute passenger:test_which_passenger
** Execute passenger:rbenv:hook
** Execute rbenv:map_bins
** Invoke images:sync_from (first_time)
** Execute images:sync_from
00:00 images:sync_from
      01 rsync -avx --delete <user>@<host>.com:/var/www/webapp/shared/public/system/images shared/images
      01 receiving file list ... done
      01
      01 sent 16 bytes  received 394 bytes  63.08 bytes/sec
      01 total size is 625172  speedup is 1524.81
    ✔ 01 stephen@localhost 6.635s
```
The ONLY time the host key verification fails is when I instead invoke the block with this statement: `on primary(:app) do |host|`

**Comment by mattbrictson** [comment]
I am a bit confused why `run_locally` and `on` are nested in your example. Aren't these completely contradictory operations? My understanding is that `run_locally` is for running a command locally (i.e. without SSH) and `on` is for running commands remotely (via SSH).

```ruby
run_locally do
    on primary(:app) do |host|
```

I guess my point is, I am not surprised that this is crashing in weird ways. 😉 

What are you trying to accomplish, exactly? Could you explain the high-level behavior you are looking for? Maybe there is a better way to do it with Capistrano.

**Comment by stepheneb** [comment]
High-level goal: use rsync to efficiently replicate state of directory of uploaded images.  Pattern: replicate state from remote server to local dev system and from local dev system to remote server. Often using this pattern to first replicate from production to local dev and later from production to staging through local dev.

**Comment by stepheneb** [comment]
Here's some desc of related tasks. As the site gets bigger the transfer of an archived copy becomes unsustainable.

cap images:fetch

Upload shared/images.tgz archive to remote server and
replaces existing public/system/images

cap images:push

When the total size of the uploaded images gets larger
then these tasks will be more efficient

sync uploaded images from the remote server to shared/images

cap images:sync_from

sync images from shared/images to remote server

cap images:sync_to

sync images to shared/images from remote server

**Comment by stepheneb** [comment]
When I run rsync I'm expecting it to run on my local development computer and communicate with the primary host defined for the specific deploy target. Of course I can run the rsync process in either direction even though it is initiated from my local system.

Because I want the following to run locally and communicate with the primary host for a deploy target I assume I need to wrap it in a `run_locally` block.
 
```
 execute :rsync, '-avx --delete', "#{host.user}@#{host.hostname}:/var/www/webapp/shared/public/system/images", "shared/images"
```
When the application expands to require multiple servers if I keep the uploaded images on one server I'd like to run the rsync process against just that server. That's why I am trying to wrap the invocation in a `on primary(:app) do |host|` block.

**Comment by mattbrictson** [comment]
OK, thanks for the background. I think I see where you are going with this. Basically, you want run `rsync` (a locally-executed command), but parameterize the rsync command with the hosts you've defined in your Capistrano configuration, such that an rsync command runs for each host.

The short answer is that Capistrano is not designed to work this way. You might be able to hack something together, but I would not recommend it to the general Capistrano audience.

A rudimentary way to do what you are asking would be:

```ruby
run_locally do
  roles(:app).each do |host|
    execute :rsync, "..."
  end
end
```

I see from your original message that you already figured this out.

If you want to use only the primary host, then it is just a slight change:

```ruby
run_locally do
  host = primary(:app)
  execute :rsync, "..."
end
```

Note that you cannot combine `run_locally` with `on`. Just use plain Ruby methods and variables for iterating through the hosts.

However, even though this technique may work for you, it is not a general-purpose solution. It is also misleading. Since you are invoking `rsync` directly, and the rsync command knows nothing about Capistrano, you will not get any of Capistrano's normal SSH behavior. For example, if you've customized the `:keys`, `:port`, `:user`, or any other of Capistrano's many per-server SSH options, none of this will be automatically used by rsync.

That means that the SSH connection created by rsync and the SSH connection created by Capistrano (i.e. when you use an `on` block) will be completely different and governed by different configuration. This could potentially be very confusing, at the least. You could easily end up with situations where an SSH connection works via rsync but not via Capistrano, or vice versa.

I hope that makes it clear what is happening behind the scenes. If I've misunderstood your scenario let me know!

**Comment by stepheneb** [comment]
@mattbrictson , thanks so much for the suggestion! This is simple and works well. Am happy I can extend the cap tooling and host identification to do this task.

```
  desc "sync uploaded images from the remote server to shared/images"
  task :sync_from do
    run_locally do
      host = primary(:app)
      execute :rsync, '-avx --delete', "#{host.user}@#{host.hostname}:/var/www/webapp/shared/public/system/images", "shared/images"
    end
  end

  desc "sync images from shared/images to remote server"
  task :sync_to do
    run_locally do
      host = primary(:app)
      execute :rsync, '-avx --delete', "shared/images", "#{host.user}@#{host.hostname}:/var/www/webapp/shared/public/system/images"
    end
  end
```

**Comment by mattbrictson** [comment]
Great! Thanks for following up. I'll consider this issue to be resolved.
