### ISSUE TITLE
`as` does not use login shell

### ISSUE THREAD

**Issue by toaster** [capistrano/sshkit#400]
For reasons I cannot see the `as` command uses a sub-shell (`sh -c`) to run the commands instead of simply let `sudo` do the stuff.
However the `sh -c` is not a login shell: it does not load the profile files.
In my particular case some `PATH` entries are missing then and I therefore cannot use `as`.

**Comment by leehambley** [comment]
This is by design please see the "why does something work in SSH but not
via Capistrano" in the docs.

**Comment by toaster** [comment]
Okay, I had a quick look and if I understood it correctly it is designed so, because we are _not_ an interactive shell and therefore do _not_ want the started shell to be a login shell, right?

I think I can work around my issue by extending the `PATH` with `with` but I whish that would not be necessary.

**Comment by leehambley** [comment]
Hi Tilo, another option is to use the command map to prefix your command
with a "source" using the command map, or chain your command with "source"
by passing a string.

Alternatively under Ubuntu certain shell files are always loaded (because
of init of the shell via rsh/SSH) according to Matt, youd have to check the
Ubuntu docs for more info tho.

**Comment by leehambley** [comment]
Apparently it's .bash_profile that's always loaded on Ubuntu but YMMV

**Comment by toaster** [comment]
Hi Lee,

thanks for your further efforts. I am on Amazon Linux. So I can't use any Ubuntu magic that may or may not be there :).

I already used the command map but as it grew bigger and bigger I decided to patch the `PATH` instead.

Regarding the init files:
Because the `as` command uses `sh -c` for invoking another shell, it doesn't matter how much initialization was done by the SSH invocation. It starts a new, non-interactive Bash in compatibility mode loading no file at all. As already stated I can't check if Ubuntu does something different there.
The `.bash_profile` is only loaded if you start the Bash as login shell (`bash -l`). Especially it is never loaded if you start Bash in compatibility mode (`sh`) regardless if you use `-l` or not.

The whole Bash initialization file business is fairly complex. The man pages state that either the `BASH_ENV` (for `bash`) or the `ENV` (for `sh`) environment variables may point to an init file. But I only got this working when specifying directly in the `sudo` command as in: `sudo -u … (BASH_)ENV=… (ba)sh …`. And with `-c` it only works for `bash` not for `sh`.
However … the `sudo` command is out of reach if I want to use `as`.

If you already had the whole non-interactive / non-interactive login / interactive / interactive login shell discussion I assume that you made your decision on good knowledge and will go with my workaround. But maybe it would be worth the effort to provide more flexibility to the `as` command and make it possible to let it invoke `sh` as non-interactive login shell (`sh -l`).

**Comment by mattbrictson** [comment]
Hi @toaster, I think the "Capistrano way" in this case is to explicitly initialize the `$PATH` entries that your deployment depends on. You can do this with `:default_env`. That way you don't have to worry about the particulars of the shell initialization.

```ruby
set :default_env, path: "/opt/whatever/bin:/usr/local/bin:/usr/bin"
```

**Comment by toaster** [comment]
Hi @mattbrictson, I am using SSHKit without capistrano. The `set` method is not available there AFAICS.

**Comment by mattbrictson** [comment]
My apologies. In SSHKit you can do the same thing like this:

```ruby
SSHKit.config.default_env = { path: "/opt/whatever/bin:/usr/local/bin:/usr/bin" }
```

See also: [EXAMPLES.md](https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md#run-with-default-environmental-variables)

**Comment by toaster** [comment]
I tried this and it didn't work for me, my test script:

```ruby
#!/usr/bin/env ruby

require 'sshkit'
require 'sshkit/dsl'

SSHKit.config.default_env = {path: "/opt/whatever/bin:/usr/local/bin:/usr/bin"}
on "ec2-user@my_host_here" do
  puts capture("id")
  puts capture("echo $PATH")
  as :root do
    puts capture("id")
    puts capture("echo $PATH")
  end
end
```

produced:

```
uid=500(ec2-user) gid=500(ec2-user) groups=500(ec2-user),10(wheel)
/usr/local/bin:/bin:/usr/bin:/opt/aws/bin
uid=0(root) gid=0(root) groups=0(root)
/usr/local/bin:/bin:/usr/bin:/opt/aws/bin
```

**Comment by mattbrictson** [comment]
`default_env`, `with`, etc. only apply to commands executed in this format:

```ruby
execute :command, "args"
```

They will not apply in this format:

```ruby
execute "command args"
```

[Reference:](https://github.com/capistrano/sshkit#basic-usage)

> Note: In SSHKit, the first parameter of the execute / test / capture methods has a special significance. If the first parameter isn't a Symbol, SSHKit assumes that you want to execute the raw command and the as / within / with methods, SSHKit.config.umask and the comand map have no effect.

You should see the `$PATH` is working if you use:

```ruby
puts capture(:env)
```

**Comment by toaster** [comment]
Thanks @mattbrictson, that worked fine.
