### ISSUE TITLE
Keep ed25519 development dependencies in gemspec?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/sshkit#404]
`net-ssh` requires that we explicitly add the `rbnacl-libsodium`, `rbnacl`, and `bcrypt_pbkdf` gems as dependencies in order to use ed25519 SSH keys.

Since my local machine has an ed25519 key, I had temporarily added these gems to the SSHKit gemspec in order to facilitate development. The feature tests otherwise fail to run.

When I tagged and released SSHKit 1.14.0, I inadvertently [committed](https://github.com/capistrano/sshkit/commit/f57d0e06397cedc1112f026340361d6481624e4c) this addition to the gemspec:

```ruby
  gem.add_development_dependency('bcrypt_pbkdf')
  gem.add_development_dependency('rbnacl', '~> 3.4')
  gem.add_development_dependency('rbnacl-libsodium')
```

Should we keep this in or should I remove it?

**Comment by leehambley** [comment]
👍 for keeping it. I believe it's more complicated on Windows, but I don't have the whole information in my head. But I'd guess we have a small number of Windows users, and they know well enough how to look for workarounds as they have grown used to being less actively represented in FOSS. (/conjecture)

**Comment by will-in-wi** [comment]
Another vote for keeping them. With ed25519 keys becoming more popular, it's probably fine to just have this in by default.

**Comment by mattbrictson** [comment]
Great, thanks for the feedback!

**Comment by mattbrictson** [comment]
We'll keep them in; if Windows compatibility is a problem we deal with it when the time comes. 😃
