### ISSUE TITLE
Using built-in logger

### ISSUE THREAD

**Issue by mbajur** [capistrano/sshkit#406]
Hello!

I'm sorry if that question is too trivial but i really can't find any example nor related code on how to achieve what i'm trying to do.

Is it possible to use a built-in sshkit logger instead of the `puts` ? I would really love to stick to the formatting provided by sshkit rather than using puts or enginering it from scratch. I'm pretty sure there is some built-in way, i just don't know where to look :)

Thanks in advance.

**Comment by mattbrictson** [comment]
Within an `on` block, you can use these methods: `fatal error warn info debug`. They will be routed through SSHKit's logger.

Here's an example from Capistrano that uses `warn` and `info`:

https://github.com/capistrano/capistrano/blob/54f714a063a4c2b24cfd4b5e054e4ad5871a0d0c/lib/capistrano/tasks/deploy.rake#L150-L168

**Comment by mbajur** [comment]
Yes! That was it, thank you.
