### ISSUE TITLE
"Embrace String#start_with?" fails when called via Cap

### ISSUE THREAD

**Issue by UnderpantsGnome** [capistrano/sshkit#409]
Commit https://github.com/capistrano/sshkit/commit/e715e05d491bbd5c795e380d1d15019727cbc4a3

When calling `upload!` via Cap, this call fails due to `remote` being a Pathname instead of a string.

    SSHKit::Runner::ExecuteError: Exception while executing as deploy@example.com: undefined method `start_with?' for #<Pathname:/ebs/webapps/xxx/staging/releases/20171109202937>
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'

    Caused by:
    NoMethodError: undefined method `start_with?' for #<Pathname:/ebs/xxx/staging/releases/20171109202937>
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/netssh.rb:66:in `upload!'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sekrets-1.10.0/lib/sekrets/tasks/sekrets.rake:8:in `block (4 levels) in <top (required)>'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/backends/abstract.rb:29:in `run'
    /Users/xxx/vendor/bundle/ruby/2.4.0/gems/sshkit-1.15.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'

[Here is the task that's calling upload!](https://github.com/ahoward/sekrets/blob/18828c9cdd9a0e9af7f89c55053a53f9383aa55e/lib/sekrets/tasks/sekrets.rake#L8)

**Comment by mattbrictson** [comment]
Great catch, thanks for the report!

Would you be willing to open a PR for a fix? Or @sj26 could you look into this? Thanks!

**Comment by UnderpantsGnome** [comment]
Here you go https://github.com/capistrano/sshkit/pull/410
