### ISSUE TITLE
How do I run the examples?

### ISSUE THREAD

**Issue by FrankFang** [capistrano/sshkit#413]
Is it something like `bin/rake whatever` or `ruby whatever.rb`?
Sorry, I am a newbie to Rails.

**Comment by leehambley** [comment]
Hi @FrankFang thanks for your interest in SSHKit, if you can't even get it running it's probably not the best tool for you at your stage of learning. Please try checking out some videos about Ruby in general and come back when you've hit your first problems. These forums are for bugs/improvements, not for general help, StackOverflow excels in that domain. Make sure to tag your future comments with `sshkit` or `capistrano` and we'll see them

**Comment by FrankFang** [comment]
Thanks. I find the answer
```
bundle exec cap install
create whatever.rake under lib/capistrano/tasks
cap production whatever
```

It works~

**Comment by leehambley** [comment]
But you've asked about SSHKit, which is used by Capistrano, but here the usage instructions are different. Anyway, I'm glad you come along - Capistrano (as the user-facing front end) has much better tutorials and support than it's internal SSH driver (SSHKit)
