### ISSUE TITLE
upload! and file permissions

### ISSUE THREAD

**Issue by allaire** [capistrano/sshkit#423]
Hi,

I'm trying to understand how mod & file permissions work when using the `upload!`command. For some reason, when I upload from a `String.IO`, the permission is always `640`, and when I use upload from a file the uploaded file permission is set to `644`.

I see that Net::SCP has a `preserve`option, but it's obviously not working when using a String.IO.

All uploaded were done in the `/tmp` directory. my default umask is `002`, but I don't think that SCP is using it, since it doesn't use an interactive shell.

```
task :umask do
  on roles(:umask) do
    file = File.open('test.txt')
    upload! file, "/tmp/test2.txt"
    # upload! StringIO.new("Hello"), "/tmp/hello.txt"
  end
end
```

Could someone shed some lights on why the permissions on the file uploaded from a `String.IO` is not set to `644`?

Thanks!

**Comment by allaire** [comment]
Well, I think I found by reading the net-scp code, available here:

https://github.com/delano/net-scp/blob/master/lib/net/scp/upload.rb#L63

I also found out it was possible to pass a `mode`option, could be a nice addition to the doc.

`upload! StringIO.new("Hello"), "/tmp/hello.txt", mode: 0644`

**Comment by mattbrictson** [comment]
PRs to update docs are greatly appreciated! 😉

**Comment by allaire** [comment]
Will do!
