### ISSUE TITLE
[Feature Request] Ability to hide string of command using execute

### ISSUE THREAD

**Issue by NorseGaud** [capistrano/sshkit#429]
Howdy!

I'm working on the capistrano-postgresql gem and we've switched to using execute instead of test for better user experience when they run `cap setup`.

The problem: We're seeing the password in the capistrano.log and also the STDOUT.

Request: I'd love a way to wrap the `'#{fetch(:pg_password)}'` in `execute :psql, "-d #{database}", '-c', %Q{"CREATE USER \\"#{fetch(:pg_username)}\\" PASSWORD '#{fetch(:pg_password)}';"}` with something to prevent STDOUT and the log from showing it. Maybe replace it with [HIDDEN] or something.

**Comment by leehambley** [comment]
Hi @NorseGaud thanks for the issue report. The first place I can imagine looking is at a custom logger where we could do the redaction.

SSHKit and Capistrano use the same `IO.write` pass-thru scheme for writing logs that MiniTest and a few others do, and the *most* objects pass through _still structured_ the logger.

This would enable you to make a special case for when the logger gets a `Execute` type command object and redact certain fields and/or values.

How we handle that in regards of telling the logger *what* to redact is another problem, but at least I think the experimentation starts there.

**Comment by NorseGaud** [comment]
I'll play around a bit in a fork of sshkit and see if I can accomplish this easily. I'll submit a pull request for your review after that. Thanks Lee!

**Comment by NorseGaud** [comment]
Ok, ready for your review: https://github.com/capistrano/sshkit/pull/430

I'm going to bed. Been up too long 👍
