### ISSUE TITLE
Strange Nokogiri problem running a very specific command

### ISSUE THREAD

**Issue by NorseGaud** [capistrano/sshkit#437]
<pre>[1] pry(#<SSHKit::Backend::Netssh>)> execute :sudo, 'test -f /etc/systemd/system/non-active-task-cache-cleaner.service.d/EnvironmentFile'
      04 sudo test -f /etc/systemd/system/non-active-task-cache-cleaner.service.d/EnvironmentFile
      04 WARN: Unresolved specs during Gem::Specification.reset:
      04       nokogiri (~> 1.7)
      04 WARN: Clearing out unresolved specs.
      04 Please report a bug if this causes problems.
      04 /usr/lib64/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:34:in `default_gemfile': Could not locate Gemfile (Bundler::GemfileNotFound)
      04        from /usr/lib64/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:314:in `default_gemfile'
      04        from /usr/lib64/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:135:in `definition'
      04        from /usr/lib64/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:101:in `setup'
      04        from /usr/lib64/ruby/gems/2.4.0/gems/uni-alias-1.0.1/bin/test:3:in `<top (required)>'
      04        from /usr/bin/test:22:in `load'
      04        from /usr/bin/test:22:in `<main>'
SSHKit::Command::Failed: sudo exit status: 1
sudo stdout: WARN: Unresolved specs during Gem::Specification.reset:
      nokogiri (~> 1.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/lib64/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/shared_helpers.rb:34:in `default_gemfile': Could not locate Gemfile (Bundler::GemfileNotFound)
        from /usr/lib64/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:314:in `default_gemfile'
        from /usr/lib64/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:135:in `definition'
        from /usr/lib64/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:101:in `setup'
        from /usr/lib64/ruby/gems/2.4.0/gems/uni-alias-1.0.1/bin/test:3:in `<top (required)>'
        from /usr/bin/test:22:in `load'
        from /usr/bin/test:22:in `<main>'
sudo stderr: Nothing written
from /usr/local/opt/gems/gems/sshkit-1.17.0/lib/sshkit/command.rb:99:in `exit_status='
</pre>

Yet, I can do `execute :sudo, '-i test -f /etc/systemd/system/non-active-task-cache-cleaner.service.d/EnvironmentFile'` and it works

I've got nokogiri 1.8.4 installed.
ruby 2.5.0p0

**Comment by leehambley** [comment]
So the difference seems to be between `sudo …` and `sudo -i …` which makes sense given:

> -i [command]
> The -i (simulate initial login) option runs the shell specified by the password
> database entry of the target user as a login shell. This means that
> login-specific resource files such as .profile or .login will be read by the
> shell. If a command is specified, it is passed to the shell for execution via
> the shell's -c option. If no command is specified, an interactive shell is
> executed. sudo attempts to change to that user's home directory before running
> the shell. The security policy shall initialize the environment to a minimal
> set of variables, similar to what is present when a user logs in. The Command
> Environment section in the sudoers(5) manual documents how the -i option
> affects the environment in which a command is run when the sudoers policy is in
> use.

This is working as expected. Something in the shell startup files in login mode (see [here](https://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/) for more info) is doing something to the environment to make this work.

**Comment by NorseGaud** [comment]
Ah, thanks for pointing that out Lee. I didn’t look into it that far since this was being deployed onto a fresh host.
