### ISSUE TITLE
upload! using default ssh port regardless of what deploy files specify

### ISSUE THREAD

**Issue by NorseGaud** [capistrano/sshkit#440]
Howdy! Looking to use `upload!` from sshkit in the postgresql capistrano gem.
Right now, we're using 
<pre>server 'dev.growtrader.org', user: 'growtrader', roles: %w{web app db}, port: '123', :primary => true</pre>

Within the postgresql gem, I use:

<pre>
        Net::SCP.upload!(
            self.host.hostname,
            self.host.user,
            StringIO.new(pg_template(true, download!(archetype_database_yml_file))),
            archetype_database_yml_file,
            ssh: { port: self.host.port }
        )</pre>

However, even with 123 set, I'm seeing:

<pre>
 norsegaud@norsegaudnet  ~/RubymineProjects/growtrader   development ✚ ● ?  bundle exec cap development setup                                                                                                                            1 ↵  8605  17:05:59 
* ===== Postgresql Setup ===== *
 All psql commands will be run without sudo
 You can modify this in your app/config/deploy/development.rb by setting the pg_without_sudo boolean.
00:00 postgresql:generate_database_yml_archetype
      Downloading database.yml 100.0%
#<Thread:0x00007fd1c1a7e4b0@/Users/norsegaud/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        1: from /Users/norsegaud/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/norsegaud/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sshkit-1.17.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as growtrader@dev.growtrader.org: Connection refused - connect(2) for 192.168.56.210:22 (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as growtrader@dev.growtrader.org: Connection refused - connect(2) for 192.168.56.210:22

Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for 192.168.56.210:22

Tasks: TOP => postgresql:generate_database_yml_archetype
(See full trace by running task with --trace)
</pre>

Does upload! support a different ssh port?

**Comment by leehambley** [comment]
I believe that we agreed on setting SSH port and similar via a .SSH/config
file, you can specify one to load, can you Try it?

**Comment by NorseGaud** [comment]
Well, this is weird... I tried it again this morning and it's working. I must have screwed something up. I can use port: 123 on the server line and also upload! in the gem.

Thanks!
