### ISSUE TITLE
local backend does not return last newline

### ISSUE THREAD

**Issue by grosser** [capistrano/sshkit#450]
```Ruby
SSHKit::Backend::Local.new(&->(*){ capture "echo", "1" }).run
"1"
```

**Comment by mattbrictson** [comment]
The `capture` method strips trailing white space by default. This applies to all backends. You can disable this behavior using `strip: false`, like this:

```ruby
SSHKit::Backend::Local.new(&->(*){ capture "echo", "1", strip: false }).run
```

Hope that helps!

**Comment by grosser** [comment]
Thx for the quick reply.
Kinda strange default, but I guess changing this now would cause lots of
havoc :D
