### ISSUE TITLE
allow silencing upload/download

### ISSUE THREAD

**Issue by grosser** [capistrano/sshkit#456]
would be great if I could pass `verbose: false` or so to these to make things a little less noisy ... atm I'm using a global silence which is not threadsafe ...

```ruby
  def silence_sshkit
    old = SSHKit.config.output_verbosity
    SSHKit.config.output_verbosity = :WARN
    yield
  ensure
    SSHKit.config.output_verbosity = old
  end
```

**Comment by will-in-wi** [comment]
That would make sense to me. Would you be willing to attempt a patch?

**Comment by grosser** [comment]
I'll take a look
