### ISSUE TITLE
GPL copyleft affects any software deployed with Capistrano?

### ISSUE THREAD

**Issue by mattbrictson** [capistrano/sshkit#47]
Hi,

Perhaps this is a question for a lawyer rather than a GitHub issue, but I thought I would ask here anyway:

If my (proprietary) software requires Capistrano for deployment, and Capistrano (v3) in turn requires SSHKit, which is GPL software, does that mean that my software is bound by the terms of the GPL? After all, SSHKit is in my Gemfile.lock and "incorporated" into my program for the purposes of deployment.

For some perspective, popular deployment tools like Chef and Puppet are notably *not* GPL, and in fact [Puppet switched from GPL to Apache license in 2011](http://puppetlabs.com/blog/relicensing-puppet-to-apache-2-0) specifically to address concerns from companies wanting to use Puppet but worried about licensing.

Maybe I am being paranoid here. What is your stance on this?

Thanks.

**Comment by mattbrictson** [comment]
Closed in favor of #277

**Comment by benders** [comment]
@leehambley Thank you! I know that relicensing is a huge hassle on-top of all the work that you've already done. So I wanted to let you know that we appreciate it (without gumming up that other much busier thread).

**Comment by leehambley** [comment]
Cheers @benders always difficult to relicense, but totally worth it in this case, I'd just forgotten I was bein a licence nazi by default :)
