### ISSUE TITLE
Is there travis-ci.com build?

### ISSUE THREAD

**Issue by colorbox** [capistrano/sshkit#504]
Latest build on travis was on the `travis-ci.org` linked from README.
https://travis-ci.org/github/capistrano/sshkit

Is there any plans to migrate `travis-ci.com` or GitHub Action?

https://travis-ci.org/github/capistrano/sshkit/builds

https://blog.travis-ci.com/2021-05-07-orgshutdown#:~:text=We're%20aiming%20to%20sunset,will%20no%20longer%20run%20successfully.

**Comment by mattbrictson** [comment]
Good question! No, there are no plans to migrate to travis-ci.com. I think GitHub Actions would be more appropriate.

Would you be interested in opening a PR to set up GitHub Actions and becoming a contributor to the project?

**Comment by colorbox** [comment]
OK, I try it.
