### ISSUE TITLE
multiline bash with if

### ISSUE THREAD

**Issue by neovatar** [capistrano/sshkit#62]
If have the following bash block:

```
  execute <<-EOBLOCK
    set -e
    if [ -L #{current_path} ]; then
      service #{service_name} stop
    fi
    rm -f #{current_path}
    ln -s #{release_path} #{current_path}
    service #{service_name} start
  EOBLOCK
```

what sshkit/capistrano runs on the server is

`/usr/bin/env if [ -L /var/play/hello-b/release/CURRENT ]; then; service play-hello-b stop; fi; rm -f /var/play/hello-b/release/CURRENT; ln -s /var/play/hello-b/release/hello-b-1.0-SNAPSHOT /var/play/hello-b/release/CURRENT; service play-hello-b start`

the problem seems to be the added semicolon after the then statement `then;`, this causes an error.

I am not sure, if I am doing something wrong or if this is a problem with the muliline command conversion in sshkit.

**Comment by hron84** [comment]
@leehambley for the record: the most occurring problem is `then;` and `do;` so it would be a good workaround (would cover most of the issues) if oneliner logic could take care about this two exact situation. 

(Sorry for necroposting, i just googled around the problem and i landed on this page)
