### ISSUE TITLE
`background` hangs when ran in `within` blocks

### ISSUE THREAD

**Issue by mumoshu** [capistrano/sshkit#73]
Hi,

Thanks a lot for the great software!
I'm getting more and more excited as I see how flexible SSHKit (and of course Capistrano 3) is :)

I have found that `background` hangs when used within `within` blocks.
I'm running Capistrano 3.0.1 with SSHKit on Ubuntu 12.04.

With the code below, run `cap test will_hang1` to reproduce the hangs. You can also run `cap test wont_hang` to see how to fix those.

As far as I know, the problem here is that `nohup` seems to hang when executed after `cd`.
We can probably avoid the hangs by changing `background` to emit shell commands like `cd the_dir; ( ( nohup the_command &>/dev/null ) & )`.

I suspect that the issue is arrising from Net::SSH([ref](https://github.com/capistrano/sshkit/blob/master/lib/sshkit/backends/netssh.rb#L70)). So I believe that we can do a work-around on SSHKit side or just document it in [Usage Examples](https://github.com/capistrano/sshkit/blob/master/EXAMPLES.md).

```ruby
# config/deploy/test.rb

task :will_hang1 do
  on roles(:local) do
    within '/home/vagrant' do
      background 'nc -l 12345'
    end
  end
end

# FYI, Don't do the below, too!
task :will_hang2 do
  on roles(:local) do
    execute "( ( cd /home/vagrant; nohup nc -l 12345 &>/dev/null ) & )"
  end
end

task :wont_hang do
  on roles(:local) do
    execute "cd /home/vagrant; ( ( nohup nc -l 12345 &>/dev/null ) & )"
  end
end
```

Regards,
Yusuke

**Comment by leehambley** [comment]
[Opened a new issue, background will be removed.](https://github.com/capistrano/sshkit/issues/332)
