### ISSUE TITLE
upload!() should honor within()

### ISSUE THREAD

**Issue by docwhat** [capistrano/sshkit#89]
The `upload!()` (and `download()`) methods should both honor `within()` for relative paths.

Example:

```
within '/tmp/' do
  upload! '/etc/hosts', 'should-be-in-tmp'
end
```

I expect the file `should-be-in-tmp` to be in `/tmp/` but instead it is in the user's home directory.

Ciao!

**Comment by mikz** [comment]
Duplicate of #329 which is more active.

**Comment by leehambley** [comment]
Thanks for the GC hint @docwhat
